In [ ]:
#Connect google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Load Dataset
df=pd.read_csv('/content/drive/MyDrive/US_Accident/US_Accidents_March23.csv',nrows=100000)

In [ ]:
df.head() #Checking top 5 column

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [ ]:
df.info() #Checking column details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     100000 non-null  object
 1   Source                 100000 non-null  object
 2   Severity               100000 non-null  int64
 3   Start_Time             100000 non-null  object
 4   End_Time               100000 non-null  object
 5   Start_Lat              100000 non-null  float64
 6   Start_Lng              100000 non-null  float64
 7   End_Lat                0 non-null       float64
 8   End_Lng                0 non-null       float64
 9   Distance(mi)           100000 non-null  float64
 10  Description            100000 non-null  object
 11  Street                 100000 non-null  object
 12  City                   99999 non-null   object
 13  County                 100000 non-null  object
 14  State                  100000 non-null  object
 15  Zipcode                99993 non-null   object
 16  Country                100000 non-null  object
 17  Timezone               99993 non-null   object
 18  Airport_Code           99993 non-null   object
 19  Weather_Timestamp      98946 non-null   object
 20  Temperature(F)         98409 non-null   float64
 21  Wind_Chill(F)          4322 non-null    float64
 22  Humidity(%)            98144 non-null   float64
 23  Pressure(in)           98708 non-null   float64
 24  Visibility(mi)         98154 non-null   float64
 25  Wind_Direction         98936 non-null   object
 26  Wind_Speed(mph)        76180 non-null   float64
 27  Precipitation(in)      7368 non-null    float64
 28  Weather_Condition      98396 non-null   object
 29  Amenity                100000 non-null  bool
 30  Bump                   100000 non-null  bool
 31  Crossing               100000 non-null  bool
 32  Give_Way               100000 non-null  bool
 33  Junction               100000 non-null  bool
 34  No_Exit                100000 non-null  bool
 35  Railway                100000 non-null  bool
 36  Roundabout             100000 non-null  bool
 37  Station                100000 non-null  bool
 38  Stop                   100000 non-null  bool
 39  Traffic_Calming        100000 non-null  bool
 40  Traffic_Signal         100000 non-null  bool
 41  Turning_Loop           100000 non-null  bool
 42  Sunrise_Sunset         99999 non-null   object
 43  Civil_Twilight         99999 non-null   object
 44  Nautical_Twilight      99999 non-null   object
 45  Astronomical_Twilight  99999 non-null   object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 26.4+ MB

In [ ]:
#Checking missing values
df.isnull().sum()

ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
End_Lat                  100000
End_Lng                  100000
Distance(mi)                  0
Description                   0
Street                        0
City                          1
County                        0
State                         0
Zipcode                       7
Country                       0
Timezone                      7
Airport_Code                  7
Weather_Timestamp          1054
Temperature(F)             1591
Wind_Chill(F)             95678
Humidity(%)                1856
Pressure(in)               1292
Visibility(mi)             1846
Wind_Direction             1064
Wind_Speed(mph)           23820
Precipitation(in)         92632
Weather_Condition          1604
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset                1
Civil_Twilight                1
Nautical_Twilight             1
Astronomical_Twilight         1
dtype: int64